In [ ]:
#numpy kütüphanesinin en teml elemanı array(dizi)'dir.
#arrayer listelerden(py kullanıyor) 50 kat daha hızlıdır.
#liste ya da tuple benzeri nesneleri array'e dönüştürebiliriz.      np.array([1,2,3])
#built-in hazır fonksiyonlar yardımıyla da array oluşturabiliriz    np.arange(),np.linspace() ...
#rastgele data    np.random()
#.rshape() arrayin şeklini değiştiriyor(eleman sayısı sabit !)
#.nditer() birden fazla dizinin elemanlarını ziyaret etme esnekliği sağlar

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr0d=np.array(53)   #0 boyutlu
arr0d

array(53)

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6]])  #2 boyutlu
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.arange(12,39,3)  #(12,39) aralığında 3 artan

array([12, 15, 18, 21, 24, 27, 30, 33, 36])

In [ ]:
np.linspace(10,20,5)  #(10,20] aralığında eşit aralıklarla artan 5 sayı

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
np.logspace(1,3,15)   #(1,3] aralığında 10^1 ile 10^3 arasında logaritmik artan 15 sayı

array([  10.        ,   13.89495494,   19.30697729,   26.82695795,
         37.2759372 ,   51.79474679,   71.9685673 ,  100.        ,
        138.94954944,  193.06977289,  268.26957953,  372.75937203,
        517.94746792,  719.685673  , 1000.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3),dtype=int)  #2 satır 3 sütunluk 0 matrisi(int tipinde)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(5)  #5x5 birim matris oluşturur(heryer 0, diagonal(köşegen) 1)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5)  #5 tane [0,1] aralığında random 5 sayı

array([0.32980937, 0.23218558, 0.22619364, 0.82436518, 0.87183643])

In [ ]:
np.random.rand(3,4)

array([[0.47909013, 0.83771725, 0.30363029, 0.27194258],
       [0.66797963, 0.33669409, 0.4107817 , 0.0073636 ],
       [0.64022827, 0.4615373 , 0.82429757, 0.67274716]])

In [ ]:
np.random.randint(15,50,15)

array([41, 39, 48, 23, 28, 35, 29, 48, 19, 19, 44, 18, 41, 29, 18])

In [ ]:
np.random.randint(1,100,(3,5))

array([[67, 46, 66, 22, 68],
       [15, 58, 55, 51, 51],
       [53, 86, 26, 59, 94]])

In [ ]:
yasin=np.random.randint(0,50,(4,6))
yasin

array([[25, 38, 32, 40, 10, 14],
       [ 4, 33, 12, 28, 14, 21],
       [40, 33, 40, 42, 42, 21],
       [14, 30, 36, 30, 42,  4]])

In [ ]:
yasin.ndim    #ndim kaç boyutlu olduğunu yazar

2

In [ ]:
yasin.shape   #shape matrisin kaça kaçlık olduğunu yazar

(4, 6)

In [ ]:
x=np.arange(53,62)
x[4]

np.int64(57)

In [ ]:
arr=np.random.randint(1,100,10)

In [ ]:
arr.max()

np.int64(97)

In [ ]:
arr.argmax()   #max'ın kaçıncı indexte bulunduğu

np.int64(6)

In [ ]:
arr.dtype      #type'ının hangi tür olduğunu yazar

dtype('int64')

In [ ]:
arr=arr.astype(float)  # .astype metodu ile arraylerin dtype'ını değiştirebiliriz
arr

array([11., 45., 54., 81., 69., 56., 97., 31., 25., 86.])

In [ ]:
arr.dtype

dtype('float64')

--------------
**ders2**

In [ ]:
#.rshape() methodu kullanılırken hesaplamak istemediğimiz boyut yerine -1 koyarız bu otomatik bir şekilde tamamlar !!!
arr3d=np.arange(120).reshape(5,3,-1)
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119]]])

In [ ]:
arr1=np.array([1,4,6,8])
arr2=np.array([3,5,8,9])
arr1.__add__(arr2)        #magic func.(buradaki add toplama işlemini yapar)

array([ 4,  9, 14, 17])

--------------------------

In [ ]:
arr=np.random.randint(0,10,10)

In [ ]:
arr.sum()

np.int64(53)

In [ ]:
arr.var()

np.float64(11.809999999999999)

In [ ]:
arr.std()

np.float64(3.4365680554879163)

-----------------------

#numpy arraylerini birleştirme np.concatenate([arr1,arr2],axis=1)

In [ ]:
arr1=np.array([[1,2,3],[5,6,7]])
arr2=np.array([[5,6,7],[8,9,10]])
np.concatenate([arr1,arr2],axis=1)   #axis=0 yanyana(satır), axis=1 altalta(sütun)

array([[ 1,  2,  3,  5,  6,  7],
       [ 5,  6,  7,  8,  9, 10]])

In [ ]:
#np.hstack()     	Yatay birleştirir	np.concatenate(..., axis=1)
#np.vstack()	    Dikey birleştirir	np.concatenate(..., axis=0)
#np.concatenate()	Daha esnek, axis parametresi gerekir

-----------------

In [ ]:
# Aradığımız değerlerin indexlerini döndürme np.where()
arr=np.array([1,2,5,6,7,7,9,2,2,2])
np.where(arr==2)

(array([1, 7, 8, 9]),)

In [ ]:
#choice()   arrayden random 1 sayı çeker
arr=np.array([1,2,5,6,7,7,9,2,2,2])
np.random.choice(arr)

np.int64(2)

In [1]:
#Yasin